Controllers/ProgrammeController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using UniPlanner.Areas.Identity.Data;
using UniPlanner.Models;

namespace UniPlanner.Controllers
{  [Authorize]
    public class ProgrammeController : Controller
    {
        
        private readonly UniPlannerContext _context;

        public ProgrammeController(UniPlannerContext context)
        {
            _context = context;
        }

        // GET: Programme
        public async Task<IActionResult> Index(
     string sortOrder,
     string currentFilter,
     string SearchString,
     int? pageNumber)
        {

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSort"] = sortOrder == "name" ? "name_desc" : "name";

            if (_context.Programme == null)
            {
                return Problem("Entity set 'UniversityPlanner.Programme'  is null.");
            }

            if (SearchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            var name = from n in _context.Programme
                       select n;

            if (!String.IsNullOrEmpty(SearchString)) //filter feature
            {
                name = name.Where(s => s.Name!.Contains(SearchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    name = name.OrderByDescending(s => s.Name);
                    break;
               
                case "name":
                    name = name.OrderBy(s => s.Name);
                    break;

                default:
                    break;
            }
            int pageSize = 10;
            return View(await PaginatedList<Programme>.CreateAsync(name.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Programme/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Programme == null)
            {
                return NotFound();
            }

            var programme = await _context.Programme
                .FirstOrDefaultAsync(m => m.ProgrammeID == id);
            if (programme == null)
            {
                return NotFound();
            }

            return View(programme);
        }

        // GET: Programme/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Programme/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProgrammeID,Name")] Programme programme)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(programme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(programme);
        }

        // GET: Programme/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Programme == null)
            {
                return NotFound();
            }

            var programme = await _context.Programme.FindAsync(id);
            if (programme == null)
            {
                return NotFound();
            }
            return View(programme);
        }

        // POST: Programme/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProgrammeID,Name")] Programme programme)
        {
            if (id != programme.ProgrammeID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(programme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProgrammeExists(programme.ProgrammeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(programme);
        }

        // GET: Programme/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Programme == null)
            {
                return NotFound();
            }

            var programme = await _context.Programme
                .FirstOrDefaultAsync(m => m.ProgrammeID == id);
            if (programme == null)
            {
                return NotFound();
            }

            return View(programme);
        }

        // POST: Programme/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Programme == null)
            {
                return Problem("Entity set 'UniPlannerContext.Programme'  is null.");
            }
            var programme = await _context.Programme.FindAsync(id);
            if (programme != null)
            {
                _context.Programme.Remove(programme);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProgrammeExists(int id)
        {
          return (_context.Programme?.Any(e => e.ProgrammeID == id)).GetValueOrDefault();
        }
    }
}

Controllers/UniProgrammeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using UniPlanner.Areas.Identity.Data;
using UniPlanner.Models;

namespace UniPlanner.Controllers
{
    [Authorize]
    public class UniProgrammeController : Controller
    {
        private readonly UniPlannerContext _context;

        public UniProgrammeController(UniPlannerContext context)
        {
            _context = context;
        }

        // GET: UniProgramme
        public async Task<IActionResult> Index(
    string sortOrder,
    string currentFilter,
    string SearchString,
    int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["nameSort"] = sortOrder == "name" ? "name_desc" : "name";
            ViewData["rankScoreSort"] = sortOrder == "rankScore" ? "rankScore_desc" : "rankScore";
            ViewData["universitySort"] = sortOrder == "university" ? "university_desc" : "university";

            if (_context.UniProgramme == null)
            {
                return Problem("Entity set 'UniversityPlanner.UniProgramme'  is null.");
            }

            if (SearchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                SearchString = currentFilter;
            }

            var name = from n in _context.UniProgramme.Include(u => u.Programme).Include(u => u.UniversityInfo)
                select n;

            if (!String.IsNullOrEmpty(SearchString)) //filter feature
            {
                name = name.Where(s => s.Programme.Name!.Contains(SearchString));

            }
            

            switch (sortOrder)
            {
                case "name_desc":
                    name = name.OrderByDescending(s => s.Programme.Name);
                    break;
                case "rankScore_desc":
                    name = name.OrderByDescending(s => s.RankScore);
                    break;
                case "university_desc":
                    name = name.OrderByDescending(s => s.UniversityInfo.Name);
                    break;
                case "name":
                    name = name.OrderBy(s => s.Programme.Name);
                    break;
                case "rankScore":
                    name = name.OrderBy(s => s.RankScore);
                    break;
                case "university":
                    name = name.OrderBy(s => s.UniversityInfo.Name);
                    break;
                default:
                    break;
            }
            

            int pageSize = 10;
            return View(await PaginatedList<UniProgramme>.CreateAsync(name.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: UniProgramme/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UniProgramme == null)
            {
                return NotFound();
            }

            var uniProgramme = await _context.UniProgramme
                .Include(u => u.Programme)
                .Include(u => u.UniversityInfo)
                .FirstOrDefaultAsync(m => m.UniProgrammeID == id);
            if (uniProgramme == null)
            {
                return NotFound();
            }

            return View(uniProgramme);
        }

        // GET: UniProgramme/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["ProgrammeID"] = new SelectList(_context.Programme, "ProgrammeID", "Name");
            ViewData["UniversityInfoID"] = new SelectList(_context.UniversityInfo, "UniversityInfoID", "Name");
            return View();
        }

        // POST: UniProgramme/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("UniProgrammeID,UniversityInfoID,ProgrammeID,Link,RankScore")] UniProgramme uniProgramme)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(uniProgramme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProgrammeID"] = new SelectList(_context.Programme, "ProgrammeID", "ProgrammeID", uniProgramme.ProgrammeID);
            ViewData["UniversityInfoID"] = new SelectList(_context.UniversityInfo, "UniversityInfoID", "UniversityInfoID", uniProgramme.UniversityInfoID);
            return View(uniProgramme);
        }

        // GET: UniProgramme/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UniProgramme == null)
            {
                return NotFound();
            }

            var uniProgramme = await _context.UniProgramme.FindAsync(id);
            if (uniProgramme == null)
            {
                return NotFound();
            }
            ViewData["ProgrammeID"] = new SelectList(_context.Programme, "ProgrammeID", "Name", uniProgramme.ProgrammeID);
            ViewData["UniversityInfoID"] = new SelectList(_context.UniversityInfo, "UniversityInfoID", "Name", uniProgramme.UniversityInfoID);
            return View(uniProgramme);
        }

        // POST: UniProgramme/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("UniProgrammeID,UniversityInfoID,ProgrammeID,Link,RankScore")] UniProgramme uniProgramme)
        {
            if (id != uniProgramme.UniProgrammeID)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(uniProgramme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UniProgrammeExists(uniProgramme.UniProgrammeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProgrammeID"] = new SelectList(_context.Programme, "ProgrammeID", "ProgrammeID", uniProgramme.ProgrammeID);
            ViewData["UniversityInfoID"] = new SelectList(_context.UniversityInfo, "UniversityInfoID", "UniversityInfoID", uniProgramme.UniversityInfoID);
            return View(uniProgramme);
        }

        // GET: UniProgramme/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UniProgramme == null)
            {
                return NotFound();
            }

            var uniProgramme = await _context.UniProgramme
                .Include(u => u.Programme)
                .Include(u => u.UniversityInfo)
                .FirstOrDefaultAsync(m => m.UniProgrammeID == id);
            if (uniProgramme == null)
            {
                return NotFound();
            }

            return View(uniProgramme);
        }

        // POST: UniProgramme/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UniProgramme == null)
            {
                return Problem("Entity set 'UniPlannerContext.UniProgramme'  is null.");
            }
            var uniProgramme = await _context.UniProgramme.FindAsync(id);
            if (uniProgramme != null)
            {
                _context.UniProgramme.Remove(uniProgramme);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UniProgrammeExists(int id)
        {
          return (_context.UniProgramme?.Any(e => e.UniProgrammeID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout-8CG8163KZY.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniPlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniPlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniPlanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UniversityInfo">UniversityInfo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Programme">Programme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UniProgramme">UniProgramme</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MajorsOffered">MajorsOffered</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml"></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UniPlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UniPlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UniPlanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <!--header containing the tables-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UniversityInfo" asp-action="Index">University Info</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Programme" asp-action="Index">Programmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UniProgramme" asp-action="Index">Programmes Offered</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MajorsOffered" asp-action="Index">Majors Offered</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial.cshtml"></partial><!--links to register and login pages-->
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UniPlanner - By <b>Saaid Faraz</b>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>